version: "3.7"
services:
  app:
    build:
      context: .
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    env_file:
      - .env  # Load environment variables from .env file

  db:
    image: postgres:13
    container_name: db_app
    env_file:
      - .env  # Load environment variables from .env file
    environment:
      POSTGRES_USER: ${DB_USER}      # Reference variable from .env
      POSTGRES_PASSWORD: ${DB_PASS}  # Reference variable from .env
      DB_NAME: ${POSTGRES_DB}          # Reference variable from .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: redis_app
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: your_secure_password
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

volumes:
  postgres_data: